export type AllElementsType =
  | HTMLAnchorElement
  | HTMLAreaElement
  | HTMLBRElement
  | HTMLBaseElement
  | HTMLBodyElement
  | HTMLButtonElement
  | HTMLCanvasElement
  | HTMLDListElement
  | HTMLDataElement
  | HTMLDataListElement
  | HTMLDetailsElement
  | HTMLDialogElement
  | HTMLDirectoryElement
  | HTMLDivElement
  | HTMLEmbedElement
  | HTMLFieldSetElement
  | HTMLFontElement
  | HTMLFormElement
  | HTMLFrameElement
  | HTMLFrameSetElement
  | HTMLHRElement
  | HTMLHeadElement
  | HTMLHeadingElement
  | HTMLHtmlElement
  | HTMLIFrameElement
  | HTMLImageElement
  | HTMLInputElement
  | HTMLLIElement
  | HTMLLabelElement
  | HTMLLegendElement
  | HTMLLinkElement
  | HTMLMapElement
  | HTMLMarqueeElement
  | HTMLMediaElement
  | HTMLMenuElement
  | HTMLMetaElement
  | HTMLMeterElement
  | HTMLModElement
  | HTMLOListElement
  | HTMLObjectElement
  | HTMLOptGroupElement
  | HTMLOptionElement
  | HTMLOutputElement
  | HTMLParagraphElement
  | HTMLParamElement
  | HTMLPictureElement
  | HTMLPreElement
  | HTMLProgressElement
  | HTMLQuoteElement
  | HTMLScriptElement
  | HTMLSelectElement
  | HTMLSlotElement
  | HTMLSourceElement
  | HTMLSpanElement
  | HTMLStyleElement
  | HTMLTableCaptionElement
  | HTMLTableCellElement
  | HTMLTableColElement
  | HTMLTableElement
  | HTMLTableRowElement
  | HTMLTableSectionElement
  | HTMLTemplateElement
  | HTMLTextAreaElement
  | HTMLTimeElement
  | HTMLTitleElement
  | HTMLTrackElement
  | HTMLUListElement
  | HTMLUnknownElement;
